version: "3.8"

networks:
  network:
    driver: bridge

services:
  go-service:
    build: .
    depends_on:
      redis:
        condition: service_healthy
      pgsql:
        condition: service_healthy
    container_name: docker-first
    environment:
      #PGS
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_WALLET_DATABASE=counter_data
      - PG_TIMEOUT=200ms

      #REDIS
      - REDIS_PORT=6379
      - REDIS_TIMEOUT=200ms

      #common
      - NAME=Anton
    ports:
      - "8080:8080"
    networks:
      - network
    user: root
    restart: on-failure

  redis:
    image: redis:4-alpine

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s

    ports:
      - "6379:6379"

    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    networks:
      - network
    restart: on-failure
  pgsql:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - network